### PR TITLE
Enable configuration for Module Generator

### PR DESCRIPTION
**Pull request by noxify**
This PR allows us to change the configuration for the module generation.

Based on my Issue #91

### CODE REVIEW

**Comment by nWidart** [comment]
:+1: 

What happens if the configured path is empty ?
Would be nice that if it's empty, no stubs get generated. :smiley:

**Comment by noxify** [comment]
Currently, we will run into an error (if I'm not wrong).
I will add this later.

Thanks @nWidart for the suggestion.

**Comment by noxify** [comment]
@nWidart - something like this?

I think, it's the easiest way to have an flag to enable/disable the stub functionality :)

**Comment by nWidart** [comment]
:+1: I like it a lot! Very nice addition, thank you. :)

**Comment by noxify** [comment]
thanks YOU for your suggestion :)
Now we have to wait for @gravitano :)

**Comment by noxify** [comment]
thanks :)

**Pull request merged**
